version: "3.2"

services:
    database:
        image: postgres:11.4
        volumes:
            - ./data/db:/var/lib/postgresql/data

    node:
        build:
            context: ./docker/node
        volumes:
            - ./:/var/app:rw
        working_dir: /var/app
