version: '3.2'

services:
    http:
        image: nginx:latest
        depends_on:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/app:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:cached
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:cached

    database:
        image: postgres:11.4
        volumes:
            - ./data/db:/var/lib/postgresql/data

    php:
        depends_on:
            - database
        build:
            context: ./docker/php
        volumes:
            - ./:/var/app:rw
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
        working_dir: /var/app

    tools:
        build:
            context: ./docker/tools
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./:/var/app:rw
            - ./docker/tools/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
        working_dir: /var/app

    node:
        depends_on:
            - php
        build:
            context: ./docker/node
        volumes:
            - ./:/var/app:rw
        working_dir: /var/app
