version: '3.7'

networks:
    app:

services:
    database:
        container_name: MagicSchoolManager_Database
        hostname: database
        environment:
            MYSQL_DATABASE: magicschoolmanager
            MYSQL_USER: symfony_magicschoolmanager
            MYSQL_PASSWORD: magicschoolmanager
            MYSQL_ROOT_PASSWORD: magicschoolmanager
        networks:
            - app
        ports:
            - 3306:3306
        image: mariadb:latest
        volumes:
            - ./data/db:/var/lib/mysql

    php:
        depends_on:
            - database
        container_name: MagicSchoolManager_PHP
        hostname: php
        build:
            context: ./docker/php
        working_dir: /var/app
        networks:
            - app
        ports:
            - 9000:9000
        volumes:
            - ./:/var/app
            - ./logs/symfony:/var/app/var/log
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

    http:
        depends_on:
            - php
        container_name: MagicSchoolManager_HTTP
        hostname: http
        image: nginx:latest
        networks:
            - app
        ports:
            - 80:80
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./:/var/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./docker/nginx/conf.d:/etc/nginx/conf.d

    node:
        depends_on:
            - php
        container_name: MagicSchoolManager_Node
        build:
            context: ./docker/node
        volumes:
            - ./:/var/app
        working_dir: /var/app
