version: '3.7'

services:
    database:
        container_name: MagicSchoolManager_Database
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: magicschoolmanager
            MYSQL_USER: symfony_magicschoolmanager
            MYSQL_PASSWORD: magicschoolmanager
            MYSQL_ROOT_PASSWORD: magicschoolmanager
        ports:
            - 3306:3306
        volumes:
            - ./docker/database:/etc/mysql/conf.d:cached
            - ./data/db:/var/lib/mysql:rw

    php:
        container_name: MagicSchoolManager_PHP
        depends_on:
            - database
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./:/var/app:rw
            - ./logs/symfony:/var/app/var/log:cached
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
        working_dir: /var/app

    http:
        container_name: MagicSchoolManager_HTTP
        depends_on:
            - php
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/app:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:cached
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:cached

    node:
        container_name: MagicSchoolManager_Node
        depends_on:
            - php
        build:
            context: ./docker/node
        volumes:
            - ./:/var/app:rw
        working_dir: /var/app
