version: 2

aliases:
    - &restore_vendor_cache
        keys:
            - vendor-{{ checksum "composer.lock" }}
    - &save_vendor_cache
        keys: vendor-{{ checksum "composer.lock" }}
        paths:
            - ~/data/vendor
    - &build_images
        - checkout
        - run: make build
        - run: make start
    - &attach_workspace
        attach_workspace:
            - at: ~/data
    - &dependencies
        - checkout
        - restore_cache: *restore_vendor_cache
        - run: make dependencies
        - save_cache: *save_vendor_cache
        - persist_to_workspace:
              root: .
              paths:
                  - vendor
    - &phpunit
        - checkout
        - run: make phpunit
    - &behat
        - checkout
        - run: make behat

    - &deps
        - "Dependencies"

    - &build_environment
        working_directory: ~/data
        build:
            machine:
                docker_layer_caching: true

workflows:
    version: 2
    master:
        jobs:
            - "Build Image"
            - "Dependencies"
            - "PHPUnit":
                  requires: *deps
            - "Behat":
                  requires: *deps

jobs:
    "Build Images":
        <<<: *build_environment
        steps: *build_images
    "Dependencies":
        <<<: *build_environment
        steps: *dependencies
    "PHPUnit":
        <<<: *build_environment
        steps: *phpunit
    "Behat":
        <<<: *build_environment
        steps: *behat
