version: 2

jobs:
    build:
        machine: true
        steps:
            - checkout
            - setup_remote_docker:
                docker-layer_caching: true
            - run: make build
            - run: make start


