version: 2

jobs:
    build:
        docker:
            - image: cimg/php:8.0.3-node
        steps:
            - checkout
            - run: sudo apt install -y php8.0-intl
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.lock" }}
                    - composer-v1-
            - run: composer install -n --prefer-dist
            - save_cache:
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package-lock.json" }}
                      - composer-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
            - run: vendor/bin/behat
            - run: vendor/bin/simple-phpunit
            - run: phpdbg -qrr vendor/bin/infection
