version: 2

aliases:
    - &restore_vendor_cache
        keys:
            - vendor-{{ checksum "composer.lock" }}

    - &save_vendor_cache
        key: vendor-{{ checksum "composer.lock" }}
        paths:
            - ~/data/vendor

    - &build_images
        - checkout
        - run: make build
        - run: make start

    - &attach_workspace
        attach_workspace:
            at: ~/data

    - &vendor_install
        name: Install Vendors
        command: make dependencies

    - &dependencies
        - checkout
        - *attach_workspace
        - restore_cache: *restore_vendor_cache
        - run: *vendor_install
        - save_cache: *save_vendor_cache
        - persist_to_workspace:
              root: .
              paths:
                  - vendor

    - &phpunit
        - checkout
        - *attach_workspace
        - run: make phpunit

    - &behat
        - checkout
        - *attach_workspace
        - run: make behat

    - &infection
        - checkout
        - *attach_workspace
        - run: make infection

    - &phpstan
        - checkout
        - *attach_workspace
        - run: make phpstan

    - &phan
        - checkout
        - *attach_workspace
        - run: make phan

    - &csfix
        - checkout
        - *attach_workspace
        - run: make cs-fix

    - &phpa
        - checkout
        - *attach_workspace
        - run: make phpa

    - &phpcpd
        - checkout
        - *attach_workspace
        - run: make phpcpd

    - &phpmnd
        - checkout
        - *attach_workspace
        - run: make phpmnd

    - &psalm
        - checkout
        - *attach_workspace
        - run: make psalm

    - &phpmd
        - checkout
        - *attach_workspace
        - run: make phpmd

    - &dephpend_metrics
        - checkout
        - *attach_workspace
        - run: make dephpend-metrics

    - &dephpend_uml
        - checkout
        - *attach_workspace
        - run: make dephpend-uml

    - &dephpend_dsm
        - checkout
        - *attach_workspace
        - run: make dephpend-dsm

    - &phpmetrics
        - checkout
        - *attach_workspace
        - run: make phpmetrics

    - &phploc
        - checkout
        - *attach_workspace
        - run: make phploc

    - &pdepend
        - checkout
        - *attach_workspace
        - run: make pdepend

    - &deps
        - "Build Images"
        - "Dependencies"

    - &test_deps
        - "PHPUnit"
        - "Behat"
        - "Infection"

    - &qa_deps
        - "PHPStan"
        - "Phan"
        - "CS-Fix"
        - "PHP Assumptions"
        - "PHP Copy/Paste Detector"
        - "PHP Magic Number Detector"
        - "Psalm"

    - &build_environment
        working_directory: ~/data
        machine:
            docker_layer_caching: true

workflows:
    version: 2
    master:
        jobs:
            - "Build Images"
            - "Dependencies"
            - "PHPUnit":
                  requires: *deps
            - "Behat":
                  requires: *deps
            - "Infection":
                  requires: *deps
            - "PHPStan":
                  requires: *test_deps
            - "Phan":
                  requires: *test_deps
            # Not 7.4 compatible ATM
            #- "CS-Fix":
            #      requires: *test_deps
            - "PHP Assumptions":
                  requires: *test_deps
            - "PHP Copy/Paste Detector":
                  requires: *test_deps
            - "PHP Magic Number Detector":
                  requires: *test_deps
            - "Psalm":
                  requires: *test_deps
            - "PHP MD":
                  requires: *qa_deps
            - "Dephpend Metrics":
                  requires: *qa_deps
            - "Dephpend UML":
                  requires: *qa_deps
            - "Dephpend DSM":
                  requires: *qa_deps
            - "PHP Metrics":
                  requires: *qa_deps
            - "PHP Loc":
                  requires: *qa_deps
            - "PDepend":
                  requires: *qa_deps

jobs:
    "Build Images":
        <<: *build_environment
        steps: *build_images
    "Dependencies":
        <<: *build_environment
        steps: *dependencies
    "PHPUnit":
        <<: *build_environment
        steps: *phpunit
    "Behat":
        <<: *build_environment
        steps: *behat
    "Infection":
        <<: *build_environment
        steps: *infection
    "PHPStan":
        <<: *build_environment
        steps: *phpstan
    "Phan":
        <<: *build_environment
        steps: *phan
    "CS-Fix":
        <<: *build_environment
        steps: *csfix
    "PHP Assumptions":
        <<: *build_environment
        steps: *phpa
    "PHP Copy/Paste Detector":
        <<: *build_environment
        steps: *phpcpd
    "PHP Magic Number Detector":
        <<: *build_environment
        steps: *phpmnd
    "Psalm":
        <<: *build_environment
        steps: *psalm
    "PHP MD":
        <<: *build_environment
        steps: *phpmd
    "Dephpend Metrics":
        <<: *build_environment
        steps: *dephpend_metrics
    "Dephpend UML":
        <<: *build_environment
        steps: *dephpend_uml
    "Dephpend DSM":
        <<: *build_environment
        steps: *dephpend_dsm
    "PHP Metrics":
        <<: *build_environment
        steps: *phpmetrics
    "PHP Loc":
        <<: *build_environment
        steps: *phploc
    "PDepend":
        <<: *build_environment
        steps: *pdepend
