version: 2

jobs:
    build:
        docker:
            - image: circleci/php:7.3.5-fpm-stretch-node
        working_directory: ~
        steps:
            - checkout
            - run: sudo composer self-update
            - restore_cache:
                  keys:
                      - composer-v1-{{ checksum "composer.lock" }}
                      - composer-v1-
            - run: composer install -n --prefer-dist
            - save_cache:
                  key: composer-v1-{{ checksum "composer.lock" }}
                  paths:
                      - vendor
            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules
            - run: yarn build
            - run: php bin/phpunit
            - run: vendor/bin/php-cs-fixer fix src/
