parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            App\Domain\MagicSchool\Identity\Ancestry\Generator\AncestryGeneratorInterface $ancestryGenerator: '@default.ancestry_generator'
            App\Domain\MagicSchool\Identity\Lastname\Provider\LastNameProviderInterface: '@default.lastname_provider'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    default.ancestry_generator:
        class: App\Domain\MagicSchool\Identity\Ancestry\Generator\DefaultAncestryGenerator

    default.lastname_provider:
        class: App\Domain\MagicSchool\Identity\Lastname\Provider\DefaultLastnameProvider

    App\Domain\MagicSchool\School\Repository\SchoolRepositoryInterface:
        alias: App\Adapter\School\Repository\DoctrineSchoolRepository
