parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            App\Domain\MagicSchool\Ancestry\Generator\AncestryGeneratorInterface $ancestryGenerator: '@default.ancestry_generator'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    default.ancestry_generator:
        class: App\Domain\MagicSchool\Ancestry\Generator\DefaultAncestryGenerator
