parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            App\Domain\MagicSchool\Identity\Ancestry\Generator\AncestryGeneratorInterface $ancestryGenerator: '@default.ancestry_generator'
            App\Domain\MagicSchool\Identity\Lastname\Provider\LastNameProviderInterface: '@default.lastname_provider'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    doctrine.orm.quote_strategy.escaping:
        class: PSCS\Doctrine\ORM\Mapping\EscapingQuoteStrategy

    default.ancestry_generator:
        class: App\Domain\MagicSchool\Identity\Ancestry\Generator\DefaultAncestryGenerator

    default.lastname_provider:
        class: App\Domain\MagicSchool\Identity\Lastname\Provider\DefaultLastnameProvider
